### ISSUE TITLE
Fix issues due to capitalization

### ISSUE THREAD

**Issue by lbianchi-lbl** [gmlc-dispatches/sample-data#1]
e.g. from https://github.com/gmlc-dispatches/dispatches/runs/7294448606?check_suite_focus=true.

```txt
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/dispatches_sample_data/rts_gmlc/timeseries_data_files/HYDRO/DAY_AHEAD_hydro.csv'
```

See also:

- https://github.com/gmlc-dispatches/dispatches/pull/119#issuecomment-1164969845
- https://github.com/bknueven/RTS-GMLC/commit/d93b196f664a1dbff72bc5a255c9d8c54832a268

**Comment by lbianchi-lbl** [comment]
Pinging @bknueven for advice: do you think changing this similarly to what you did in bknueven/RTS-GMLC@d93b196 would make sense for this repo? If so, I can apply those changes (or any alternative you might suggest) and test that it works using maybe a minimal test workflow in this repository (in addition to the complete notebooks in DISPATCHES).

**Comment by bknueven** [comment]
> Pinging @bknueven for advice: do you think changing this similarly to what you did in bknueven/RTS-GMLC@d93b196 would make sense for this repo? If so, I can apply those changes (or any alternative you might suggest) and test that it works using maybe a minimal test workflow in this repository (in addition to the complete notebooks in DISPATCHES).

Yes, let's just apply the same patch here.
